# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-24 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=20)),
                ('Provider', models.CharField(max_length=20)),
                ('Message', models.TextField(max_length='200')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Origin', models.CharField(max_length=20)),
                ('Destination', models.CharField(max_length=20)),
                ('Truck_Type', models.CharField(max_length=20)),
                ('Number_Of_Trucks', models.CharField(max_length=20)),
                ('Date_of_Journey', models.CharField(max_length=20)),
                ('Time', models.CharField(max_length=30)),
                ('Weight', models.CharField(max_length=20)),
                ('Material_Name', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Name', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=20)),
            ],
        ),
    ]
